<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-12-10T09:50:24 IST" name="Failed suite [Regression]" finished-at="2022-12-10T09:50:40 IST" duration-ms="15832">
    <groups>
    </groups>
    <test started-at="2022-12-10T09:50:24 IST" name="Test on Chrome(failed)" finished-at="2022-12-10T09:50:40 IST" duration-ms="15832">
      <class name="testscripts.TC_001">
        <test-method is-config="true" signature="setup()[pri:0, instance:testscripts.TC_001@1e66f1f5]" started-at="2022-12-10T09:50:24 IST" name="setup" finished-at="2022-12-10T09:50:27 IST" duration-ms="2949" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_001()[pri:0, instance:testscripts.TC_001@1e66f1f5]" started-at="2022-12-10T09:50:27 IST" name="TC_001" finished-at="2022-12-10T09:50:35 IST" duration-ms="7736" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failing..]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failing..
at org.testng.Assert.fail(Assert.java:110)
at testscripts.TC_001.TC_001(TC_001.java:16)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at testscripts.FailedRunner.main(FailedRunner.java:19)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_001 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testscripts.TC_001@1e66f1f5]" started-at="2022-12-10T09:50:35 IST" name="tearDown" finished-at="2022-12-10T09:50:40 IST" duration-ms="5121" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testscripts.TC_001 -->
    </test> <!-- Test on Chrome(failed) -->
  </suite> <!-- Failed suite [Regression] -->
</testng-results>
